
# Site settings
destination: ./_site
title: Herr Ackermann Yuriy
email: ackermann.yuriy@gmail.com
description: "Ackermann Yuriy personal webpage."
baseurl: ""
url: "https://herrniemand.github.io/"
twitter_username: 
github_username:  herrniemand
deviantart_username: hrniemand

# Build settings
markdown: redcarpet
pygments: true
permalink: pretty