
# Site settings
destination: ./_site
title: Ackermann Yuriy
email: ackermann.yuriy@gmail.com
description: "Ackermann Yuriy personal webpage."
baseurl: ""
url: "http://nieman.de/"
twitter_username: 
github_username:  herrniemand
deviantart_username: hrniemand

# Build settings
markdown: redcarpet
# highlighter: pygments
permalink: pretty
